### ISSUE TITLE
Respect @SuppressWarnings("all")

### ISSUE THREAD

**Issue by leventov** [amaembo/huntbugs#22]

**Comment by amaembo** [comment]
It [should work](https://github.com/amaembo/huntbugs/blob/3fff9d6a573695280b97414eb90589a5b404d778/huntbugs/src/main/java/one/util/huntbugs/filter/AnnotationFilters.java), but to use it, you have to implement custom annotation starting with Suppress and anding with Warning. I suggest this:

~~~~java
@interface SuppressHuntBugsWarning {
  String value();
}
~~~~

And use it `@SuppressHuntBugsWarning("all")` or `@SuppressHuntBugsWarning("*")`.

Standard `java.lang.SuppressWarnings` does not work, because it has source retention, so it does not appear in bytecode.

**Comment by leventov** [comment]
Thanks @amaembo. FindBugs's SuppressFBWarnings will work?

**Comment by amaembo** [comment]
Seems unlikely due to ending -s. If you want to reuse it, consider posting a pull-request to support Suppress...Warning**s** annotations as well.
